http:
  host: 'localhost'
  port: 4011

  # If you are using a reverse proxy like Nginx,
  # you can enable this option to get the client's IP address.
  # Learn more at https://expressjs.com/en/guide/behind-proxies.html
  trust_proxy: false

db:
  # Type of database setting to use.
  type: 'mysql'

  mysql:
    host: 'localhost'
    port: 3306
    user: 'root'
    password: ''
    db: 'salgu'
    synchronize: true
    logging: false
    ssl: false

auth:
  # This follows JwtModuleOptions from @nestjs/jwt.
  jwt:
    secret: 'DO NOT USE THIS SECRET IN PRODUCTION!'
    signOptions:
      # Change this to a shorter time in production.
      expiresIn: '365d'

cors:
  whitelist:
    - 'http://localhost:4010'

swagger:
  enabled: true
  path: '/api-docs'

drive:
  path_length: 1024
  name_length: 255

  # Maximum file size in bytes.
  max_file_size: 100 * 1024 * 1024

  # Root prefix for all file/directory paths.
  root: '/My Drive'

storage:
  # File storage providers.
  providers:
    # Saves files to the local filesystem.
    local:
      # If it's a relative path, it will be relative
      # to salgu-back-end root,
      # which is the directory containing this project's package.json.
      path: './.storage/'
      enabled: true
